server.port=8080

api.security.token.secret=MinhaChaveSecreta

spring.application.name=agenda
spring.datasource.url=jdbc:postgresql://localhost:5432/agenda_db
spring.datasource.username=laoni09
spring.datasource.password=Ewrxby65*
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

#debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true